---
title: "Berry Project -- Strawberry Data Report"
author: "Ruxin Liu"
date: "10/13/2020"
output: pdf_document
---

# Introduction

# Methodology
### Data cleaning and variable selection

# Results and Discussion

# Conclusion

# Appendix
## Code

## Importing the data 

```{r}
# Load the data
library(tidyverse)
library(magrittr)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
berry <- read_csv("berries.csv", col_names = TRUE)
```

```{r}
# look at number of unique values in each column
berry %>% summarize_all(n_distinct) -> unique
# make a list of the columns with only one unique value
one <- which(unique[1,]==1)
# remove the 1-unique columns from the dataset
berry %<>% select(-all_of(one))
# State name and the State ANSI code are (sort of) redundant -- keep the name only
berry %<>% select(-4)
```

```{r}
# Select data on Strawberries only from the berry data 
strawberry <- berry %>% filter((Commodity == "STRAWBERRIES") & (Period == "YEAR"))
strawberry %<>% select(-c(Period, Commodity)) 
```

```{r}
# The original format of one specific domain type 
# (CHEMICAL, INSECTICIDE: (CYFLUMETOFEN= 138831)) is not processed successfully 
# with the separate function, therefore they need to be changed manually. 
manual <- c(1036, 1148, 1258, 1368, 1480, 1977, 2075, 2171, 2267, 2365, 
                       2469, 2542, 2613, 2684, 2757, 2985, 3019, 3052, 3085, 3120)
strawberry$`Domain Category`[manual] <- "CHEMICAL, INSECTICIDE: (CYFLUMETOFEN = 138831)"
```

```{r}
# Organize the column data item which contains lots of information in a cell
# unique(strawberry$`Data Item`)
strawberry %<>% separate(`Data Item`, c("s1", "s2"), sep = "-")
strawberry %<>% separate(s1, c("berry", "type"), sep = ",")
strawberry %<>% separate(s2, c("data_item", "unit"), sep = ",")
```


```{r}
unique(strawberry$berry)
# Since all the data selected are about strawberries, there is no need to 
# contain name of berries anymore
strawberry %<>% select(-berry)
```

```{r}
# Organize the column Domain
strawberry %<>% separate(Domain, c("Domain_1", "Domain_2"), sep = ", ")
```

```{r}
# Organize the column Domain Category
strawberry %<>% separate(`Domain Category`, c("DC_1", "DC_2"), sep = ", ")
strawberry %<>% separate(DC_1, c("DC_1_left", "DC_1_right"), sep = ": ")
strawberry %<>% separate(DC_2, c("DC_2_left", "DC_2_right"), sep = ": ") 
```

```{r}
# Check and delete the redundant variables 
paste(strawberry$Domain_1, strawberry$DC_1_left) %>% unique
strawberry %<>%  select(-DC_1_left) 
```

```{r}
# Check and delete the redundant variables 
paste(strawberry$Domain_2, strawberry$DC_2_left) %>% unique
strawberry %<>%  select(-DC_2_left) 
```

```{r}
# Change all NA values into a space
strawberry[is.na(strawberry)] <- " "
strawberry %<>% mutate(Domain_1 = "CHEMICAL", Domain_1 = "") 
strawberry %<>% mutate(Chemical = str_trim(paste(Domain_1, Domain_2)))
strawberry %<>% mutate(market = str_trim(type))
strawberry %<>% mutate(harvest = str_trim(data_item))
```

```{r}
strawberry %<>% rename(chem_family = DC_1_right, materials = DC_2_right)
#All the rows with information on chem_family have no information on Chemical, 
# so it is reasonable to combine these columns.
strawberry %<>% mutate(chemical = str_trim(paste(chem_family, Chemical)))
```

```{r}
strawberry %<>% separate(unit, c("u1", "u2", "u3", "u4", "u5", "u6", "u7", 
                                 "u8"), sep = " ")
# Only leave the useful information after "measure in"
strawberry[is.na(strawberry)] <- " "
strawberry %<>% mutate(units = str_trim(paste(u4, u5, u6, u7, u8)))
# Select the variables that are kept in the final data 
strawberry %<>% select(Year, State, market, harvest, materials, chemical,
                       Value, units)
```

```{r}

```

## Reference of R Packages

## Bibliography































